### ISSUE TITLE
Script works fine, but on iOS I get this error when invoking any method

### ISSUE THREAD

**Issue by inglesuniversal** [BallisticPain/nativescript-volume#4]
ERROR: ERROR ReferenceError: Can't find variable: LxVolumeManager

SAMPLE CODE:

    muteButton() {
        this.volume.mute();
    }

    unmuteButton() {
        this.volume.unmute();
    }

    volumeUp() {
        this.volume.volumeUp();
    }

    volumeDown() {
        this.volume.setVolume(0.5);
    }

**Comment by BallisticPain** [comment]
Sorry this has been 2 years since you posted this issue. I believe (without looking yet) that the LxVolumeManager was through a CocoaPod that is required for the plugin to work. I'll check.

**Comment by BallisticPain** [comment]
I did confirm LxVolumeManager is a CocoaPod that was used in this project. I had initially used another but from my recollection I found the LxVolumeManager to be more popular or suited my needs better, or possibly both.
